### ISSUE TITLE
Transpile to JS from babel

### ISSUE THREAD

**Issue by vojtatranta** [stream-utils/streaming-json-stringify#17]
UglifyJS does not understand babel and therefore I cannot build app when this package is not transpiled to js.

My proposal is to create /lib/ folder where babel could transpile ES2015+, so that it could be used bundled

**Comment by jonathanong** [comment]
> UglifyJS does not understand babel

i do not understand. this package doesn't use babel and it supports node 0.10

**Comment by vojtatranta** [comment]
ooohh, I am soo sorry, wrong repo :))
