### ISSUE TITLE
Custom separators /termination/ending

### ISSUE THREAD

**Issue by coballast** [stream-utils/streaming-json-stringify#5]
Hey,

I was wondering if you are open to the idea of having custom seperators and terminating and ending characters similar to JSONStream.stringify().

I am going to add the functionality myself, but I was curious as to whether you would be open to accepting a PR for it.

**Comment by coballast** [comment]
Whoops!

**Comment by jonathanong** [comment]
yeah i think i have it as a property on the stream, but i'll take a PR to make it easier to construct.

**Comment by jongleberry** [comment]
added in version 2.2.0!
